use_frameworks!

platform :ios, '13.0'

target 'BlinkingColorLabel_Example' do
  pod 'BlinkingColorLabel', :path => '../'

  target 'BlinkingColorLabel_Tests' do
    inherit! :search_paths

    
  end
end
